////
#ifndef PRIVEXEC_VERSION_H
#define PRIVEXEC_VERSION_H

#include "config.h"

#ifdef APPVEYOR_BUILD_VERSION
#define PRIVEXEC_BUILD_VERSION APPVEYOR_BUILD_VERSION
#else
#define PRIVEXEC_BUILD_VERSION L"1.1.0.1"
#endif

#ifdef APPVEYOR_BUILD_NUMBER
#define PRIVEXEC_BUILD_NUMBER APPVEYOR_BUILD_NUMBER
#else
#define PRIVEXEC_BUILD_NUMBER 1
#endif

#endif
