#ifndef PRIVEXEC_CAPABILITIES_HPP
#define PRIVEXEC_CAPABILITIES_HPP

/// SEE:
/// https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/master/NtApiDotNet/SecurityCapabilities.cs
// 67e28d2f7237bfdbfe9602ec049ab2da30c3a6c5
// $source=Get-Content -Path .\SecurityCapabilities.cs -Raw
// Add-Type -TypeDefinition $source

namespace priv {
constexpr const wchar_t *KnownCapabilityNames[] = {
    L"ID_CAP_ACCESSIBILITY_CLIENT",
    L"ID_CAP_ACCESS_FAMILY_NOTES_API",
    L"ID_CAP_ACCESS_REMINDER_IMAGES",
    L"ID_CAP_ACC_MGR_ADMIN",
    L"ID_CAP_ADAPTIVE_BRIGHTNESS_CONTROL",
    L"ID_CAP_ADVERTISING_CONFIG",
    L"ID_CAP_AIS_TOKEN_MANAGER",
    L"ID_CAP_APPCONTAINER_PACKAGE_CERTIFICATES",
    L"ID_CAP_APPOINTMENTS",
    L"ID_CAP_APPPREINSTALL_DIRECTORY",
    L"ID_CAP_APPPREINSTALL_EVENTS",
    L"ID_CAP_APPRESOLVER",
    L"ID_CAP_APPX_EXECUTION",
    L"ID_CAP_APP_STORE_PURCHASE_HISTORY",
    L"ID_CAP_AUDIO_EVENTSND",
    L"ID_CAP_AUDIO_INTERNAL",
    L"ID_CAP_AUDIO_ROUTING_CONTROLLER",
    L"ID_CAP_AUDIO_SETTINGS",
    L"ID_CAP_AUTHHOST",
    L"ID_CAP_BACKGROUND_EXECUTION_MANAGEMENT",
    L"ID_CAP_BACKGROUND_SETTINGS_MANAGEMENT",
    L"ID_CAP_BACKGROUND_WORKER",
    L"ID_CAP_BACKUPROAMRESTORE",
    L"ID_CAP_BASEOS_UPDATEAPI",
    L"ID_CAP_BINGCLIENT_BINGCONFIGURATION",
    L"ID_CAP_BINGCLIENT_CA_INTERESTEXTRACTION",
    L"ID_CAP_BINGCLIENT_DDC",
    L"ID_CAP_BINGCLIENT_IDENTITY",
    L"ID_CAP_BINGCLIENT_OSS",
    L"ID_CAP_BINGCLIENT_SUGGESTSHIGHLIGHTS",
    L"ID_CAP_BINGCLIENT_TEE",
    L"ID_CAP_BLUETOOTH",
    L"ID_CAP_BLUETOOTH_ADMIN",
    L"ID_CAP_BMR2_MONITOR_SERVICE",
    L"ID_CAP_BMR_CONFIGURATION",
    L"ID_CAP_BMR_SYNC",
    L"ID_CAP_BROKER_NAVIGATION",
    L"ID_CAP_BROWSER_ACCESSIBILITY_SETTINGS",
    L"ID_CAP_BROWSER_FEATURE_CONTROL_KEYS",
    L"ID_CAP_BSS_AIM_INTERFACE",
    L"ID_CAP_BSS_NABSYNC_INTERFACE",
    L"ID_CAP_BSS_PUSH_INTERFACE",
    L"ID_CAP_BSS_REMINDER_INTERFACE",
    L"ID_CAP_BUILTIN_BASEPRIORITY",
    L"ID_CAP_BUILTIN_CREATEGLOBAL",
    L"ID_CAP_BUILTIN_CREATEPERMANENT",
    L"ID_CAP_BUILTIN_DEFAULT",
    L"ID_CAP_BUILTIN_IMPERSONATE",
    L"ID_CAP_BUILTIN_PROFILE",
    L"ID_CAP_BUILTIN_SETTIME",
    L"ID_CAP_BUILTIN_SHUTDOWN",
    L"ID_CAP_BUILTIN_SYMBOLICLINK",
    L"ID_CAP_BUILTIN_TCB",
    L"ID_CAP_BUTTONS",
    L"ID_CAP_CALLMESSAGING_FILTER",
    L"ID_CAP_CAMERA",
    L"ID_CAP_CA_ACTIONURI_TEST_EVENT",
    L"ID_CAP_CA_ADMIN",
    L"ID_CAP_CA_BACKGROUND_PROCESSOR",
    L"ID_CAP_CA_BACKGROUND_PROCESSOR_ADMIN",
    L"ID_CAP_CA_CONTEXT",
    L"ID_CAP_CA_DND_MANAGER",
    L"ID_CAP_CA_ENABLED",
    L"ID_CAP_CA_HISTORY",
    L"ID_CAP_CA_RULES",
    L"ID_CAP_CA_SIGNALS_GENERIC",
    L"ID_CAP_CA_SIGNALS_MANAGER",
    L"ID_CAP_CA_SIGNALS_MANAGER_ADMIN",
    L"ID_CAP_CA_UPLOAD_FOLDER",
    L"ID_CAP_CELLUX_CONFIG_READ",
    L"ID_CAP_CELL_API_ADMIN",
    L"ID_CAP_CELL_API_COMMON",
    L"ID_CAP_CELL_API_LOCATION",
    L"ID_CAP_CELL_API_MESSAGING",
    L"ID_CAP_CELL_API_MODEMLOGGING",
    L"ID_CAP_CELL_API_OEM_PASSTHROUGH",
    L"ID_CAP_CELL_API_TELEPHONY",
    L"ID_CAP_CELL_API_UICC",
    L"ID_CAP_CELL_API_UICC_LOWLEVEL",
    L"ID_CAP_CELL_CELLMGR",
    L"ID_CAP_CELL_CMCSPWWAN_PLUS",
    L"ID_CAP_CELL_MSFT_UICC_DATASTORE",
    L"ID_CAP_CELL_OEM_UICC_DATASTORE",
    L"ID_CAP_CELL_RCSPRESENCE",
    L"ID_CAP_CELL_VIDEOTELEPHONY",
    L"ID_CAP_CELL_WNF",
    L"ID_CAP_CELL_WNF_ADMIN",
    L"ID_CAP_CELL_WNF_PII",
    L"ID_CAP_CHAMBER_PROFILE_CODE_INSTALLTEMP_RWD",
    L"ID_CAP_CHAMBER_PROFILE_CODE_NITEMP_RW",
    L"ID_CAP_CHAMBER_PROFILE_CODE_R",
    L"ID_CAP_CHAMBER_PROFILE_CODE_RW",
    L"ID_CAP_CHAMBER_PROFILE_DATA_LIVETILES_RWD",
    L"ID_CAP_CHAMBER_PROFILE_DATA_MEDIA_RWD",
    L"ID_CAP_CHAMBER_PROFILE_DATA_PLATFORMDATA_ALL",
    L"ID_CAP_CHAMBER_PROFILE_DATA_R",
    L"ID_CAP_CHAMBER_PROFILE_DATA_RW",
    L"ID_CAP_CHAMBER_PROFILE_DATA_SHELLCONTENT_R",
    L"ID_CAP_CHAMBER_PROFILE_DATA_SHELLCONTENT_RWD",
    L"ID_CAP_CLIPBOARD",
    L"ID_CAP_COMMANDCHANNEL",
    L"ID_CAP_COMMS_APPLICATIONS",
    L"ID_CAP_COMMS_COMMON",
    L"ID_CAP_COMMS_SERVICES",
    L"ID_CAP_COMMS_SETTINGS",
    L"ID_CAP_CONTACTS",
    L"ID_CAP_CONTENTSHARING",
    L"ID_CAP_CORTANA_RULES_DB",
    L"ID_CAP_CREATE_PROCESS_IN_CHAMBER",
    L"ID_CAP_CREDENTIAL_COLLECTION_UI",
    L"ID_CAP_CRITICAL_DATA",
    L"ID_CAP_CSP_BMR_PROVISION",
    L"ID_CAP_CSP_DMCLIENT",
    L"ID_CAP_CSP_FOUNDATION",
    L"ID_CAP_CSP_LOCATION",
    L"ID_CAP_CSP_MAIL",
    L"ID_CAP_CSP_NODECACHE",
    L"ID_CAP_CSP_OEM",
    L"ID_CAP_CSP_PHONE",
    L"ID_CAP_CSP_W4_APPLICATION",
    L"ID_CAP_CSP_WIFI_HOTSPOT",
    L"ID_CAP_DATACOLLECTION_ACTIVITY",
    L"ID_CAP_DATACOLLECTION_COLLECTOR",
    L"ID_CAP_DATACOLLECTION_RAWETW",
    L"ID_CAP_DATAPLANUSAGE",
    L"ID_CAP_DATAPLANUSAGE_ADMIN",
    L"ID_CAP_DCP",
    L"ID_CAP_DEBUG",
    L"ID_CAP_DEBUG_FOLDERS",
    L"ID_CAP_DEBUG_NAVIGATION",
    L"ID_CAP_DEVELOPERUNLOCK",
    L"ID_CAP_DEVELOPERUNLOCK_API",
    L"ID_CAP_DEVELOPERUNLOCK_CODEDUI",
    L"ID_CAP_DEVICE_LOCK",
    L"ID_CAP_DEVICE_LOCK_ADMIN",
    L"ID_CAP_DEVICE_MANAGEMENT",
    L"ID_CAP_DEVICE_MANAGEMENT_ADMIN",
    L"ID_CAP_DEVICE_MANAGEMENT_BOOTSTRAP",
    L"ID_CAP_DEVICE_MANAGEMENT_SECURITY_POLICIES",
    L"ID_CAP_DIAGNOSTIC_CLIENT",
    L"ID_CAP_DISPLAY_CONTROL",
    L"ID_CAP_DMCLIENT_APPMGMT",
    L"ID_CAP_DO_NOT_DISTURB",
    L"ID_CAP_DRIVE_MODE_ADMIN",
    L"ID_CAP_DUASVC",
    L"ID_CAP_DU_AGENT",
    L"ID_CAP_DU_CORE_API",
    L"ID_CAP_DU_CSP",
    L"ID_CAP_DU_MIGRATION_MANAGER_STATUS",
    L"ID_CAP_DU_MIGRATION_WNF_EVENTS",
    L"ID_CAP_DU_MIGRATOR_PROVISIONING_STATUS_MICROSOFT",
    L"ID_CAP_DU_MIGRATOR_PROVISIONING_STATUS_OEM",
    L"ID_CAP_DU_MIGRATOR_STATUS_MICROSOFT",
    L"ID_CAP_DU_MIGRATOR_STATUS_OEM",
    L"ID_CAP_DU_PROVISIONING",
    L"ID_CAP_DU_SHARED_DATA",
    L"ID_CAP_DU_USS",
    L"ID_CAP_DU_UX",
    L"ID_CAP_DU_UX_FEATURE_DISCOVERY",
    L"ID_CAP_EAS_CREDENTIALS",
    L"ID_CAP_EDM_CACHE_RWDELETE",
    L"ID_CAP_EDM_CACHE_WRITE",
    L"ID_CAP_ENDPOINTDISCOVERY",
    L"ID_CAP_ENROLLMENT",
    L"ID_CAP_ENROLLMENT_ADMIN",
    L"ID_CAP_ENROLLMENT_POLL",
    L"ID_CAP_ENROLLMENT_RENEW",
    L"ID_CAP_ENTERPRISERESOURCESTORE",
    L"ID_CAP_ENTERPRISE_AUTHENTICATION",
    L"ID_CAP_ENTERPRISE_ENROLLMENT",
    L"ID_CAP_ENTERPRISE_SERVICE",
    L"ID_CAP_ENTERPRISE_SHARED_DATA",
    L"ID_CAP_ETW_PROFILER",
    L"ID_CAP_EVERYONE",
    L"ID_CAP_EVERYONE_INROM",
    L"ID_CAP_EXTERNAL_DISPLAY",
    L"ID_CAP_FAILURE_REPORT_CONTENT_PROVIDER",
    L"ID_CAP_FINDMYPHONE",
    L"ID_CAP_FOREGROUND_TASK_MANAGER",
    L"ID_CAP_GAMERSERVICES",
    L"ID_CAP_GLOBALIZATION_SETTINGS",
    L"ID_CAP_HTTP_ACCEPT_LANGUAGE_HEADER",
    L"ID_CAP_ICS_RO",
    L"ID_CAP_ICS_RW",
    L"ID_CAP_IDENTITY_DEVICE",
    L"ID_CAP_IDENTITY_DEVICE_1ST_PARTY",
    L"ID_CAP_IDENTITY_USER",
    L"ID_CAP_IDENTITY_USER_1ST_PARTY",
    L"ID_CAP_IDM_IMAGE_CACHE",
    L"ID_CAP_IMMERSIVE_SHELL",
    L"ID_CAP_INPUT_CORE",
    L"ID_CAP_INPUT_FEATURES",
    L"ID_CAP_INPUT_INJECTION",
    L"ID_CAP_INPUT_LOCALES",
    L"ID_CAP_INPUT_SERVICE",
    L"ID_CAP_INSTALL_CERTIFICATES",
    L"ID_CAP_INTENTTEXTRACTION_OPTIN",
    L"ID_CAP_INTERNAL_DEPLOYMENT",
    L"ID_CAP_INTERNET_EXPLORER_BROWSER_HISTORY",
    L"ID_CAP_INTERNET_EXPLORER_DATA_OPTIMIZATION",
    L"ID_CAP_INTERNET_EXPLORER_FAVORITES",
    L"ID_CAP_INTERNET_EXPLORER_HKCU_WRITE",
    L"ID_CAP_INTERNET_EXPLORER_HKLM_SECURITY_SETTINGS",
    L"ID_CAP_INTERNET_EXPLORER_INTRANET_ZONE_SETTINGS",
    L"ID_CAP_INTERNET_EXPLORER_REMOTEDEBUGGING",
    L"ID_CAP_INTERNET_EXPLORER_ROAMING",
    L"ID_CAP_INTERNET_EXPLORER_SEARCH_PROVIDER_KEYS_HKCU",
    L"ID_CAP_INTEROPSERVICES",
    L"ID_CAP_ISV_CAMERA",
    L"ID_CAP_KEYBOARD",
    L"ID_CAP_KIDZONE_ADMIN",
    L"ID_CAP_KIDZONE_CUSTOMIZATION",
    L"ID_CAP_LANGUAGEUNDERSTANDING",
    L"ID_CAP_LASS_ADMIN",
    L"ID_CAP_LASS_REMOTELOCK",
    L"ID_CAP_LEGACY_VOICEMAIL_HANDLER",
    L"ID_CAP_LEXICONUPDATE",
    L"ID_CAP_LIVEID",
    L"ID_CAP_LIVETOKEN_WNF_EVENTS",
    L"ID_CAP_LOCATION",
    L"ID_CAP_LOCATION_ADMIN",
    L"ID_CAP_LOCATION_BTPOLICY",
    L"ID_CAP_LOCATION_GNSSDRIVER",
    L"ID_CAP_MAP",
    L"ID_CAP_MAP_ADMIN",
    L"ID_CAP_MAP_WRITE",
    L"ID_CAP_MEDIALIB",
    L"ID_CAP_MEDIALIB_AUDIO",
    L"ID_CAP_MEDIALIB_INT",
    L"ID_CAP_MEDIALIB_PHOTO",
    L"ID_CAP_MEDIALIB_PHOTO_FULL",
    L"ID_CAP_MEDIALIB_PLAYBACK",
    L"ID_CAP_MEDIALIB_VIDEO",
    L"ID_CAP_MEDIASERVICE_VOLUMELIMIT_INT",
    L"ID_CAP_MICMUTEPOLICY_BYPASS",
    L"ID_CAP_MICROPHONE",
    L"ID_CAP_MONITOR_NAVIGATION",
    L"ID_CAP_MOUSE",
    L"ID_CAP_MO_CLOUDMESSAGING",
    L"ID_CAP_MSS_BYTESTREAM_RPC",
    L"ID_CAP_MULTIMEDIA_ENCODER_HARDWARE",
    L"ID_CAP_MULTIVARIANT",
    L"ID_CAP_MULTIVARIANT_INSTALL_DATA",
    L"ID_CAP_NARRATOR_SETTINGS",
    L"ID_CAP_NATIVE_NETWORK_REPLACEMENT",
    L"ID_CAP_NAVIGATIONBAR_ADMIN",
    L"ID_CAP_NETWORKING",
    L"ID_CAP_NETWORKING_ADMIN",
    L"ID_CAP_NETWORKING_INTERNET_CLIENT",
    L"ID_CAP_NETWORKING_INTERNET_CLIENT_SERVER",
    L"ID_CAP_NETWORKING_PRIVATE_NETWORK_CLIENT_SERVER",
    L"ID_CAP_NETWORKING_VPN_ADMIN",
    L"ID_CAP_NETWORKING_VPN_PROVIDER",
    L"ID_CAP_NETWORKING_VPN_SERVICES",
    L"ID_CAP_NFC_ADMIN",
    L"ID_CAP_NOCENTER_SOUNDS",
    L"ID_CAP_NTSERVICES",
    L"ID_CAP_NVREAD",
    L"ID_CAP_NVREADWRITE",
    L"ID_CAP_O365_DISCOVERY",
    L"ID_CAP_OEMPUBLICDIRECTORY",
    L"ID_CAP_OEM_ADC",
    L"ID_CAP_OEM_CUSTOM",
    L"ID_CAP_OEM_DEPLOYMENT",
    L"ID_CAP_OFFICE_LAUNCH_URL",
    L"ID_CAP_OFFICE_MSDRM_HKCU",
    L"ID_CAP_ONENOTE_EVENTS",
    L"ID_CAP_OOBE_PRIVATE",
    L"ID_CAP_ORIENTATION_LOCK",
    L"ID_CAP_PEOPLE_EXTENSION",
    L"ID_CAP_PEOPLE_EXTENSION_IM",
    L"ID_CAP_PEOPLE_EXTENSION_MOBILE",
    L"ID_CAP_PERSONA",
    L"ID_CAP_PERSONAL_INFORMATION_IMPORT",
    L"ID_CAP_PHONEBROKER_INTERFACE",
    L"ID_CAP_PHONEDIALER",
    L"ID_CAP_PHONEPROVISIONER_DEVICEUPDATE",
    L"ID_CAP_PHONEPROVISIONER_EVENTS",
    L"ID_CAP_PHONE_2ND_PARTY",
    L"ID_CAP_PHONE_ADMIN",
    L"ID_CAP_PHONE_INTERNAL",
    L"ID_CAP_PHOTOS_SETTINGS_R",
    L"ID_CAP_PHOTOS_SETTINGS_RW",
    L"ID_CAP_PICKER_CONTRACT_UI",
    L"ID_CAP_PLATFORM_EXTENSIBILITY",
    L"ID_CAP_PLAYREADY",
    L"ID_CAP_PLAYREADY_ADMIN",
    L"ID_CAP_PM_1ST_PARTY",
    L"ID_CAP_PM_BSS",
    L"ID_CAP_PM_INSTALL",
    L"ID_CAP_POIDATASTORE",
    L"ID_CAP_POIDATASTORE_ADMIN",
    L"ID_CAP_POLICY_MANAGER",
    L"ID_CAP_POLICY_MANAGER_READONLY",
    L"ID_CAP_POWERNOTIF_USER",
    L"ID_CAP_PRESERVED_DATA",
    L"ID_CAP_PRIV_ABOUTCPL",
    L"ID_CAP_PRIV_ACCESSIBILITYCPL",
    L"ID_CAP_PRIV_ACCESSORIESCPL",
    L"ID_CAP_PRIV_ACCESSORYMGRSVC",
    L"ID_CAP_PRIV_ACCOUNTPROVSVC",
    L"ID_CAP_PRIV_ACTIONURIHOST",
    L"ID_CAP_PRIV_ADVERTISINGIDCPL",
    L"ID_CAP_PRIV_ALARMS",
    L"ID_CAP_PRIV_APHCHECK",
    L"ID_CAP_PRIV_APMUX",
    L"ID_CAP_PRIV_APPCORNER",
    L"ID_CAP_PRIV_APPPREINSTALLER",
    L"ID_CAP_PRIV_APPRESOLVERUI",
    L"ID_CAP_PRIV_APPSDATAMIGRATOR",
    L"ID_CAP_PRIV_APPXEXECUTIONSVC",
    L"ID_CAP_PRIV_AUTHHOST_MSA",
    L"ID_CAP_PRIV_AUTHHOST_WAB_A",
    L"ID_CAP_PRIV_AUTHHOST_WAB_B",
    L"ID_CAP_PRIV_AUTHHOST_WAB_C",
    L"ID_CAP_PRIV_AUTHHOST_WAB_ENTERPRISE",
    L"ID_CAP_PRIV_AUTHHOST_WAB_SSO",
    L"ID_CAP_PRIV_AUTHHOST_WAB_SSO_ENTERPRISE",
    L"ID_CAP_PRIV_AUTOTIMEUPDATE",
    L"ID_CAP_PRIV_BATTERYSAVERCPL",
    L"ID_CAP_PRIV_BLUETOOTHPBAPSVC",
    L"ID_CAP_PRIV_BMR2MONITORSVC",
    L"ID_CAP_PRIV_BMR2SCHEDULETRIGGER",
    L"ID_CAP_PRIV_BMRCPL",
    L"ID_CAP_PRIV_BMRSCHEDULETRIGGER",
    L"ID_CAP_PRIV_BRIGHTNESSCPL",
    L"ID_CAP_PRIV_BSSVC",
    L"ID_CAP_PRIV_BTAGSERVICE",
    L"ID_CAP_PRIV_BTCONNMGR",
    L"ID_CAP_PRIV_BTHAVCTPSVC",
    L"ID_CAP_PRIV_BTSERV",
    L"ID_CAP_PRIV_BTUXCPL",
    L"ID_CAP_PRIV_CALC7",
    L"ID_CAP_PRIV_CAPTURESVC",
    L"ID_CAP_PRIV_CASVCSHARED3",
    L"ID_CAP_PRIV_CELLMANAGER",
    L"ID_CAP_PRIV_CELLULARDATACOLLECTOR",
    L"ID_CAP_PRIV_CELLUX",
    L"ID_CAP_PRIV_CERTINSTALLER",
    L"ID_CAP_PRIV_CFMSVC",
    L"ID_CAP_PRIV_CGSVC",
    L"ID_CAP_PRIV_CLOUDSTORAGECPL",
    L"ID_CAP_PRIV_CMSERVICE",
    L"ID_CAP_PRIV_COMMANDCHANNEL",
    L"ID_CAP_PRIV_COMMSAPHOST",
    L"ID_CAP_PRIV_COMMSAPPLICATIONS",
    L"ID_CAP_PRIV_COMMSCERTINSTSVC",
    L"ID_CAP_PRIV_COMMSMESSAGESVC",
    L"ID_CAP_PRIV_COMMSMMSTRANSPORT",
    L"ID_CAP_PRIV_CONTACTSTOKENSVC",
    L"ID_CAP_PRIV_CONTENTSHARESVC",
    L"ID_CAP_PRIV_CONTENTSHARINGAPP",
    L"ID_CAP_PRIV_COREUIREGISTRAR",
    L"ID_CAP_PRIV_DACCERTINSTSVC",
    L"ID_CAP_PRIV_DATACOLLECTION",
    L"ID_CAP_PRIV_DATASENSESVC",
    L"ID_CAP_PRIV_DATASMART",
    L"ID_CAP_PRIV_DATETIMECPL",
    L"ID_CAP_PRIV_DCPSVC",
    L"ID_CAP_PRIV_DEBUGGERMUXNOTIFY",
    L"ID_CAP_PRIV_DIAGNOSTICSVC",
    L"ID_CAP_PRIV_DMCFGHOST",
    L"ID_CAP_PRIV_DMOMACPNETWMO",
    L"ID_CAP_PRIV_DMOMACPUSERMO",
    L"ID_CAP_PRIV_DMWAPPUSHSVC",
    L"ID_CAP_PRIV_DRIVINGMODEMANAGER",
    L"ID_CAP_PRIV_DRIVINGMODESETTINGS",
    L"ID_CAP_PRIV_DSSVC",
    L"ID_CAP_PRIV_DSTOKENCLEAN",
    L"ID_CAP_PRIV_DUACALLBACK",
    L"ID_CAP_PRIV_DUACLIENT",
    L"ID_CAP_PRIV_DUCLEANUPMIGRATOR",
    L"ID_CAP_PRIV_DUFEATUREDISCOVERY",
    L"ID_CAP_PRIV_DUMIGRATIONMANAGER",
    L"ID_CAP_PRIV_DUMIGRATIONPROVISIONERMICROSOFT",
    L"ID_CAP_PRIV_DUMIGRATIONPROVISIONEROEM",
    L"ID_CAP_PRIV_DUPOSTUPDATEUX",
    L"ID_CAP_PRIV_DUSTARTINGMIGRATOR",
    L"ID_CAP_PRIV_DUSVC",
    L"ID_CAP_PRIV_ENROLLMENTCLIENT",
    L"ID_CAP_PRIV_ENTAPPSERVICE",
    L"ID_CAP_PRIV_ENTERPRISEINSTALL",
    L"ID_CAP_PRIV_ENTERPRISEMGMSVC",
    L"ID_CAP_PRIV_ENTERPRISERING",
    L"ID_CAP_PRIV_ENTERPRISEVALIDATION",
    L"ID_CAP_PRIV_EXECMANSERVICE",
    L"ID_CAP_PRIV_FINDMYPHONE",
    L"ID_CAP_PRIV_FLYOUTDATAMIGRATOR",
    L"ID_CAP_PRIV_GROVELER",
    L"ID_CAP_PRIV_GWPCENROLLSVC",
    L"ID_CAP_PRIV_HFA",
    L"ID_CAP_PRIV_HOTSPOTHOST",
    L"ID_CAP_PRIV_HUBTILERESTOREHOST",
    L"ID_CAP_PRIV_ICSENTITLEMENTHOST",
    L"ID_CAP_PRIV_ICSSVC",
    L"ID_CAP_PRIV_INPUTSERVICE",
    L"ID_CAP_PRIV_INSTALLERWORKER",
    L"ID_CAP_PRIV_INTERNETEXPLORER",
    L"ID_CAP_PRIV_IPOVERUSB",
    L"ID_CAP_PRIV_KEYBOARDCPL",
    L"ID_CAP_PRIV_KIDZONECONFIGURATION",
    L"ID_CAP_PRIV_KIDZONECUSTOMIZATION",
    L"ID_CAP_PRIV_LASSCREDENTIALEXPIRATIONCHECK",
    L"ID_CAP_PRIV_LAUNCHAPPSVC",
    L"ID_CAP_PRIV_LEXICONUPDATE",
    L"ID_CAP_PRIV_LFSVC",
    L"ID_CAP_PRIV_LIVETOKEN",
    L"ID_CAP_PRIV_LOCATIONUXCPL",
    L"ID_CAP_PRIV_LOCKANDWALLPAPER",
    L"ID_CAP_PRIV_MEDIA",
    L"ID_CAP_PRIV_MEDIASERVICE",
    L"ID_CAP_PRIV_MIRRORCPL",
    L"ID_CAP_PRIV_MOBILEUI",
    L"ID_CAP_PRIV_MOSHOST",
    L"ID_CAP_PRIV_MSATICKETSVC",
    L"ID_CAP_PRIV_MSGIMTRANSPORT",
    L"ID_CAP_PRIV_MSGSMSTRANSPORT",
    L"ID_CAP_PRIV_MTP",
    L"ID_CAP_PRIV_MVPROVISIONHOST",
    L"ID_CAP_PRIV_MVUX",
    L"ID_CAP_PRIV_NABSYNC",
    L"ID_CAP_PRIV_NOCENTERSETTINGSCPL",
    L"ID_CAP_PRIV_NOTIFICATIONPLATFORMMIGRATOR",
    L"ID_CAP_PRIV_NOTIFSVC",
    L"ID_CAP_PRIV_OFFICE",
    L"ID_CAP_PRIV_OMADMCLIENT_ENTERPRISE",
    L"ID_CAP_PRIV_OMADMCLIENT_MOBILE_OPERATOR",
    L"ID_CAP_PRIV_OMADMPRC",
    L"ID_CAP_PRIV_OOBE",
    L"ID_CAP_PRIV_ORIENTSRV",
    L"ID_CAP_PRIV_PACMANSERVICE",
    L"ID_CAP_PRIV_PHONEAUDIOSRV",
    L"ID_CAP_PRIV_PHONEPROVISIONER",
    L"ID_CAP_PRIV_PHONEPROVISIONER_OEM",
    L"ID_CAP_PRIV_PHONESVCSG",
    L"ID_CAP_PRIV_PHOTOS",
    L"ID_CAP_PRIV_PHOTOSSVC",
    L"ID_CAP_PRIV_PIMIDXMAINT",
    L"ID_CAP_PRIV_PLACESSVC",
    L"ID_CAP_PRIV_POSTDUAPPMIGRATOR",
    L"ID_CAP_PRIV_POWERNOTIF",
    L"ID_CAP_PRIV_PROXIMITYSVC",
    L"ID_CAP_PRIV_PROXYSVC",
    L"ID_CAP_PRIV_REALWORLD-BINGCLIENT",
    L"ID_CAP_PRIV_REALWORLD-INTERESTEXTRACTION",
    L"ID_CAP_PRIV_REBOOTDEVICE",
    L"ID_CAP_PRIV_REGIONCPL",
    L"ID_CAP_PRIV_REMEMBER",
    L"ID_CAP_PRIV_RETAILDEMO",
    L"ID_CAP_PRIV_RETAILDEMOERROR",
    L"ID_CAP_PRIV_RETAILDEMOGLOB",
    L"ID_CAP_PRIV_RETAILDEMOUI",
    L"ID_CAP_PRIV_RILADAPTATION",
    L"ID_CAP_PRIV_RINGTONESANDSOUNDS",
    L"ID_CAP_PRIV_ROAMINGCPL",
    L"ID_CAP_PRIV_ROTATIONLOCKCPL",
    L"ID_CAP_PRIV_SAPISVR",
    L"ID_CAP_PRIV_SECMIGRATOR",
    L"ID_CAP_PRIV_SEMGRSVC",
    L"ID_CAP_PRIV_SETTINGS",
    L"ID_CAP_PRIV_SHELLDATAMIGRATOR",
    L"ID_CAP_PRIV_SIREPSVC",
    L"ID_CAP_PRIV_SOFTAPUX",
    L"ID_CAP_PRIV_SPEECHCPL",
    L"ID_CAP_PRIV_SPEECHUPDATE",
    L"ID_CAP_PRIV_START",
    L"ID_CAP_PRIV_STORAGESENSE",
    L"ID_CAP_PRIV_STORAGESVC",
    L"ID_CAP_PRIV_STOREDATAMIGRATOR",
    L"ID_CAP_PRIV_TASKSCHEDULERSVC",
    L"ID_CAP_PRIV_TELCPL",
    L"ID_CAP_PRIV_TELREPSVC",
    L"ID_CAP_PRIV_THEMECPL",
    L"ID_CAP_PRIV_TILEMIGRATOR",
    L"ID_CAP_PRIV_TIMEBROKER",
    L"ID_CAP_PRIV_UPDATEMGRSVC",
    L"ID_CAP_PRIV_USBCPL",
    L"ID_CAP_PRIV_USERDATASERVICE",
    L"ID_CAP_PRIV_USSREPORTING",
    L"ID_CAP_PRIV_UTKSERVICE",
    L"ID_CAP_PRIV_UTKUX",
    L"ID_CAP_PRIV_VPNUX",
    L"ID_CAP_PRIV_WALLET",
    L"ID_CAP_PRIV_WALLETSVC",
    L"ID_CAP_PRIV_WEHCSPHELPER",
    L"ID_CAP_PRIV_WEHSTART",
    L"ID_CAP_PRIV_WIFICONNSVC",
    L"ID_CAP_PRIV_WIFICPASSIST",
    L"ID_CAP_PRIV_WIFICPBROWSERUX",
    L"ID_CAP_PRIV_WIFIUDPTEST",
    L"ID_CAP_PRIV_WIFIUXBLUE",
    L"ID_CAP_PRIV_WLID2MSA",
    L"ID_CAP_PRIV_WPABSVC",
    L"ID_CAP_PRIV_WPNARRATOR",
    L"ID_CAP_PRIV_WPNCERTINSTSVC",
    L"ID_CAP_PRIV_WPTOOLS",
    L"ID_CAP_PRIV_WPTPMVSCMGRSVC",
    L"ID_CAP_PRIV_WPUITESTTOOLS",
    L"ID_CAP_PRIV_ZMEDIAQUEUESVC",
    L"ID_CAP_PRIV_ZMF",
    L"ID_CAP_PRIV_ZMF_SERVICE",
    L"ID_CAP_PROVISIONING_PACKAGE_API_ADMIN",
    L"ID_CAP_PROVISIONWPCERTIFICATE",
    L"ID_CAP_PROXIMITY",
    L"ID_CAP_PUBLIC_FOLDER_FULL",
    L"ID_CAP_PUBLISH_ALARM_STATE",
    L"ID_CAP_PUBLISH_OOBE_STATE",
    L"ID_CAP_PUSHROUTER",
    L"ID_CAP_PUSH_NOTIFICATION",
    L"ID_CAP_PUSH_SERVER",
    L"ID_CAP_QUICK_SETTINGS",
    L"ID_CAP_READGWPCERTIFICATE",
    L"ID_CAP_REBOOT_FLASHING_MODE",
    L"ID_CAP_REMEMBER_ADMIN",
    L"ID_CAP_REMEMBER_API",
    L"ID_CAP_REMOVABLE_STORAGE",
    L"ID_CAP_RESET_PHONE",
    L"ID_CAP_RESOURCE_MANAGER",
    L"ID_CAP_RETAILDEMO_BACKGROUNDIMAGE",
    L"ID_CAP_RETAILDEMO_CLIENT",
    L"ID_CAP_RETAILDEMO_GLOB_REGISTRY",
    L"ID_CAP_RETAILDEMO_OFFLINECONTENT",
    L"ID_CAP_RINGTONE_ADD",
    L"ID_CAP_ROAMING_CONFIGURATION",
    L"ID_CAP_ROTATION_MANAGER",
    L"ID_CAP_RUNTIME_CONFIG",
    L"ID_CAP_SCREENCAPTURE",
    L"ID_CAP_SCREEN_RECORDER",
    L"ID_CAP_SCREEN_RECORDER_BKG",
    L"ID_CAP_SEARCHMAPS_SHAREDCONFIG",
    L"ID_CAP_SEND_TO_ONENOTE",
    L"ID_CAP_SENSORS",
    L"ID_CAP_SETDEVICENAME",
    L"ID_CAP_SETTINGSYNC",
    L"ID_CAP_SETTINGSYNC_CONFIGURATION",
    L"ID_CAP_SETTINGS_MANAGEMENT_PROVIDER",
    L"ID_CAP_SHARED_OBJECT_DIRECTORY",
    L"ID_CAP_SHARED_USER_CERTIFICATES",
    L"ID_CAP_SHARE_DELEGATE",
    L"ID_CAP_SHELL_DEVICE_LOCK_UI_API",
    L"ID_CAP_SHELL_LAUNCH_SESSION",
    L"ID_CAP_SHELL_NAVIGATION",
    L"ID_CAP_SHELL_NOTIFICATION_CLIENT",
    L"ID_CAP_SHELL_OEM_ADMIN",
    L"ID_CAP_SHELL_RESET_NAVIGATION",
    L"ID_CAP_SHELL_TEST_CLIENT",
    L"ID_CAP_SHOW_VOLUME_CONTROL",
    L"ID_CAP_SMS",
    L"ID_CAP_SMS_COMPANION",
    L"ID_CAP_SMS_INTERCEPT_AGENT",
    L"ID_CAP_SMS_INTERCEPT_RECIPIENT",
    L"ID_CAP_SOUND_CONTROL",
    L"ID_CAP_SPEECH_GRAMMARS",
    L"ID_CAP_SPEECH_RECOGNITION",
    L"ID_CAP_SPEECH_RECOGNITION_SYSTEM",
    L"ID_CAP_SPEECH_SETTINGS",
    L"ID_CAP_SPEECH_UPDATE",
    L"ID_CAP_SPLASH_CONFIG",
    L"ID_CAP_STARTMENU_CONFIG",
    L"ID_CAP_STORAGE_MANAGEMENT",
    L"ID_CAP_SUPPRESS_MSA_CONNECT_ARD",
    L"ID_CAP_SYNC_EXTENSION",
    L"ID_CAP_SYSTEMTRAY_ADMIN",
    L"ID_CAP_SYSTEM_ALLOC_WINDOWID",
    L"ID_CAP_SYSTEM_COMPOSITOR",
    L"ID_CAP_SYSTEM_COUNTERS",
    L"ID_CAP_SYSTEM_REGISTRAR",
    L"ID_CAP_SYSTEM_WAITCURSOR",
    L"ID_CAP_TELEMETRY_ADMIN",
    L"ID_CAP_TELEMETRY_CONFIGURE",
    L"ID_CAP_TELEMETRY_STUDY",
    L"ID_CAP_TEST_NAVIGATION",
    L"ID_CAP_TILERESTOREDATA",
    L"ID_CAP_TOUCH",
    L"ID_CAP_TOUCH_TEST",
    L"ID_CAP_TPM_VSCMANAGER",
    L"ID_CAP_TS_SCHEDULES_ALL",
    L"ID_CAP_USB",
    L"ID_CAP_USER_ACTIVITY",
    L"ID_CAP_VIDEOSINK_INTERNAL",
    L"ID_CAP_VOICEMAIL",
    L"ID_CAP_VOIP",
    L"ID_CAP_VOIP_CALL_CONTROLLER",
    L"ID_CAP_VSTEST_INSTALL_FOLDER",
    L"ID_CAP_W32TIME_API",
    L"ID_CAP_WAB_RESOURCES",
    L"ID_CAP_WALLET",
    L"ID_CAP_WALLET_ADMIN",
    L"ID_CAP_WALLET_DEALS",
    L"ID_CAP_WALLET_PAYMENTINSTRUMENTS",
    L"ID_CAP_WALLET_SECUREELEMENT",
    L"ID_CAP_WALLPAPER_ADMIN",
    L"ID_CAP_WBOEXT",
    L"ID_CAP_WEBBROWSERCOMPONENT",
    L"ID_CAP_WEB_CREDENTIALS",
    L"ID_CAP_WIFI_ADMIN",
    L"ID_CAP_WIFI_BASIC",
    L"ID_CAP_WIFI_BROWSER",
    L"ID_CAP_WIFI_HOTSPOT_HOST",
    L"ID_CAP_WIFI_PROFILE_ADMIN",
    L"ID_CAP_WIFI_TILE_MANAGER",
    L"ID_CAP_WPN_PLATFORM",
    L"ID_CAP_WPN_PLATFORM_REG_KEY",
    L"ID_CAP_WPTOOLS_INSTALL_FOLDER",
    L"ID_CAP_ZMFSERVICES",
    L"ID_CAP_ZTRACE",
    L"Microsoft.firmwareRead_cw5n1h2txyewy",
    L"Microsoft.firmwareWrite_cw5n1h2txyewy",
    L"accessoryManager",
    L"activateAsUser",
    L"activity",
    L"activityData",
    L"activitySystem",
    L"allAppMods",
    L"allJoyn",
    L"allowElevation",
    L"appBroadcast",
    L"appBroadcastServices",
    L"appBroadcastSettings",
    L"appCaptureServices",
    L"appCaptureSettings",
    L"appDiagnostics",
    L"appLicensing",
    L"appManagementSystem",
    L"applicationDefaults",
    L"applicationViewActivation",
    L"appointments",
    L"appointmentsSystem",
    L"audioDeviceConfiguration",
    L"automatedAppLaunch",
    L"backgroundMediaPlayback",
    L"backgroundMediaRecording",
    L"backgroundSpatialPerception",
    L"backgroundVoIP",
    L"biometricSystem",
    L"blockedChatMessages",
    L"bluetooth",
    L"bluetooth.genericAttributeProfile",
    L"bluetooth.rfcomm",
    L"bluetoothAdapter",
    L"bluetoothDeviceSettings",
    L"bluetoothSync",
    L"bootstrapNetworkConnection",
    L"broadFileSystemAccess",
    L"browserAppList",
    L"browserCredentials",
    L"cameraProcessingExtension",
    L"capabilityAccessConsentDeviceSettings",
    L"cellularData",
    L"cellularDeviceControl",
    L"cellularDeviceIdentity",
    L"cellularMessaging",
    L"chat",
    L"chatSystem",
    L"childWebContent",
    L"chromeInstallFiles",
    L"cloudExperienceHost",
    L"cloudStore",
    L"codeGeneration",
    L"comPort",
    L"componentUiInWebContent",
    L"confirmAppClose",
    L"constrainedImpersonation",
    L"contacts",
    L"contactsSystem",
    L"contentDeliveryManagerSettings",
    L"contentRestrictions",
    L"coreShell",
    L"cortanaPermissions",
    L"cortanaSettings",
    L"cortanaSpeechAccessory",
    L"cortanaSurface",
    L"curatedTileCollections",
    L"customInstallActions",
    L"dateAndTimeDeviceSettings",
    L"dependencyTarget",
    L"developerSettings",
    L"developmentModeNetwork",
    L"deviceEncryptionManagement",
    L"deviceIdentityManagement",
    L"deviceLockManagement",
    L"deviceManagementAdministrator",
    L"deviceManagementDeviceLockPolicies",
    L"deviceManagementDmAccount",
    L"deviceManagementEmailAccount",
    L"deviceManagementFoundation",
    L"deviceManagementRegistration",
    L"deviceManagementWapSecurityPolicies",
    L"devicePortalProvider",
    L"deviceProvisioningAdministrator",
    L"deviceUnlock",
    L"diagnostics",
    L"displayDeviceSettings",
    L"documentsLibrary",
    L"dualSimTiles",
    L"email",
    L"emailSystem",
    L"enterpriseAuthentication",
    L"enterpriseCloudSSO",
    L"enterpriseDataPolicy",
    L"enterpriseDeviceLockdown",
    L"eraApplication",
    L"exclusiveResource",
    L"expandedResources",
    L"extendedBackgroundTaskTime",
    L"extendedExecutionBackgroundAudio",
    L"extendedExecutionCritical",
    L"extendedExecutionUnconstrained",
    L"featureStagingInfo",
    L"feedbackLogCollection",
    L"firstSignInSettings",
    L"flashPlayerSupport",
    L"fullFileSystemAccess",
    L"gameBarServices",
    L"gameConfigStoreManagement",
    L"gameList",
    L"gameMonitor",
    L"gamingContainerResources",
    L"gazeInput",
    L"globalMediaControl",
    L"graphicsCapture",
    L"hevcPlayback",
    L"hfxSystem",
    L"hidTelephony",
    L"holographicCompositor",
    L"holographicCompositorSystem",
    L"humanInterfaceDevice",
    L"imeSystem",
    L"inProcessMediaExtension",
    L"indexedContent",
    L"inputForegroundObservation",
    L"inputInjection",
    L"inputInjectionBrokered",
    L"inputObservation",
    L"inputSettings",
    L"inputSuppression",
    L"internetClient",
    L"internetClientServer",
    L"interopServices",
    L"keyboardDeviceSettings",
    L"kinectAudio",
    L"kinectExpressions",
    L"kinectFace",
    L"kinectGamechat",
    L"kinectRequired",
    L"kinectVideo",
    L"kinectVision",
    L"languageAndRegionDeviceSettings",
    L"languageSettings",
    L"liveIdService",
    L"localExperienceInternal",
    L"localSystemServices",
    L"location",
    L"locationHistory",
    L"locationSystem",
    L"lockScreenCreatives",
    L"lowLevel",
    L"lowLevelDevices",
    L"lpacAppExperience",
    L"lpacChromeInstallFiles",
    L"lpacClipboard",
    L"lpacCom",
    L"lpacCryptoServices",
    L"lpacEnterprisePolicyChangeNotifications",
    L"lpacIME",
    L"lpacIdentityServices",
    L"lpacInstrumentation",
    L"lpacMedia",
    L"lpacPackageManagerOperation",
    L"lpacPayments",
    L"lpacPnPNotifications",
    L"lpacPrinting",
    L"lpacServicesManagement",
    L"lpacSessionManagement",
    L"lpacWebPlatform",
    L"microphone",
    L"microsoftEdgeRemoteDebugging",
    L"mixedRealityEnvironmentInternal",
    L"mmsTransportSystem",
    L"modifiableApp",
    L"multiplaneOverlay",
    L"muma",
    L"musicLibrary",
    L"networkConnectionManagerProvisioning",
    L"networkDataPlanProvisioning",
    L"networkDataUsageManagement",
    L"networkDeviceSettings",
    L"networkDiagnostics",
    L"networkingVpnProvider",
    L"nfcSystem",
    L"notificationsDeviceSettings",
    L"objects3D",
    L"oemDeployment",
    L"oemPublicDirectory",
    L"offlineMapsManagement",
    L"oneProcessVoIP",
    L"optical",
    L"pacJsWorker",
    L"packageContents",
    L"packageManagement",
    L"packagePolicySystem",
    L"packageQuery",
    L"packageWriteRedirectionCompatibilityShim",
    L"packagedServices",
    L"perceptionMonitoring",
    L"perceptionSensorsExperimental",
    L"perceptionSystem",
    L"personalizationDeviceSettings",
    L"phoneCall",
    L"phoneCallHistory",
    L"phoneCallHistoryPublic",
    L"phoneCallHistorySystem",
    L"phoneCallSystem",
    L"phoneLineTransportManagement",
    L"picturesLibrary",
    L"pointOfService",
    L"powerDeviceSettings",
    L"preemptiveCamera",
    L"previewHfx",
    L"previewInkWorkspace",
    L"previewPenWorkspace",
    L"previewStore",
    L"previewUiComposition",
    L"privateNetworkClientServer",
    L"projectionDeviceSettings",
    L"protectedApp",
    L"proximity",
    L"radios",
    L"recordedCallsFolder",
    L"regionSettings",
    L"registryRead",
    L"relatedPackages",
    L"remoteFileAccess",
    L"remotePassportAuthentication",
    L"remoteSystem",
    L"removableStorage",
    L"resetPhone",
    L"runFullTrust",
    L"screenDuplication",
    L"searchSettings",
    L"secondaryAuthenticationFactor",
    L"secureAssessment",
    L"sensors.custom",
    L"serialCommunication",
    L"sessionImpersonation",
    L"settingSyncConfiguration",
    L"sharedMachineKeysCapability",
    L"sharedUserCertificates",
    L"shellDisplayManagement",
    L"shellExperience",
    L"shellExperienceComposer",
    L"slapiQueryLicenseValue",
    L"smbios",
    L"sms",
    L"smsSend",
    L"smsSystem",
    L"smsTransportSystem",
    L"spatialPerception",
    L"startScreenManagement",
    L"storeAppInstall",
    L"storeAppInstallation",
    L"storeConfiguration",
    L"storeLicenseManagement",
    L"storeOptionalPackageInstallManagement",
    L"systemDialog",
    L"systemDialogEmergency",
    L"systemManagement",
    L"systemRegistrar",
    L"targetedContent",
    L"targetedContentSubscription",
    L"teamEditionDeviceCredential",
    L"teamEditionExperience",
    L"teamEditionView",
    L"telemetryData",
    L"terminalPowerManagement",
    L"thumbnailCache",
    L"timezone",
    L"uiAccess",
    L"uiAutomationSystem",
    L"unvirtualizedResources",
    L"unzipFile",
    L"updateAndSecurityDeviceSettings",
    L"usb",
    L"userAccountInformation",
    L"userDataAccountSetup",
    L"userDataAccountsProvider",
    L"userDataSystem",
    L"userDataTasks",
    L"userDataTasksSystem",
    L"userManagementSystem",
    L"userNotificationListener",
    L"userPrincipalName",
    L"userSigninSupport",
    L"userSystemId",
    L"userWebAccounts",
    L"videosLibrary",
    L"visualElementsSystem",
    L"visualVoiceMail",
    L"vmWorkerProcess",
    L"voipCall",
    L"walletSystem",
    L"webPlatformMediaExtension",
    L"webcam",
    L"wiFiControl",
    L"wiFiDirect",
    L"wifiData",
    L"windowManagement",
    L"windowManagementSystem",
    L"windowsHelloCredentialAccess",
    L"windowsPerformanceCounters",
    L"xboxAccessoryManagement",
    L"xboxBroadcaster",
    L"xboxGameSpeechWindow",
    L"xboxLiveAuthenticationProvider",
    L"xboxSystemApplicationClipQuery",
    L"xboxTrackingStream",
};
// kv
struct CapabilityName {
  const wchar_t *name;
  const wchar_t *value;
};
constexpr const CapabilityName wncas[] = {
    {L"Basic - Internet Client", L"internetClient"},
    {L"Basic - Internet Client Server", L"internetClientServer"},
    {L"Basic - Private Network", L"privateNetworkClientServer"},
    {L"Basic - Pictures Library", L"picturesLibrary"},
    {L"Basic - Videos Library", L"videosLibrary"},
    {L"Basic - Music Library", L"musicLibrary"},
    {L"Basic - Documents Library", L"documentsLibrary"},
    {L"Basic - Shared User Certificates", L"sharedUserCertificates"},
    {L"Basic - Enterprise Authentication", L"enterpriseAuthentication"},
    {L"Basic - Removable Storage", L"removableStorage"},
    {L"Basic - Appointments", L"appointments"},
    {L"Basic - Contacts", L"contacts"},
    {L"LPAC - App Experience", L"lpacAppExperience"},
    {L"LPAC - Chrome Install Files", L"lpacChromeInstallFiles"},
    {L"LPAC - Clipboard", L"lpacClipboard"},
    {L"LPAC - Com", L"lpacCom"},
    {L"LPAC - Crypto Services", L"lpacCryptoServices"},
    {L"LPAC - Enterprise Policy Change Notifications", L"lpacEnterprisePolicyChangeNotifications"},
    {L"LPAC - IME", L"lpacIME"},
    {L"LPAC - Identity Services", L"lpacIdentityServices"},
    {L"LPAC - Instrumentation", L"lpacInstrumentation"},
    {L"LPAC - Media", L"lpacMedia"},
    {L"LPAC - Package Manager Operation", L"lpacPackageManagerOperation"},
    {L"LPAC - Payments", L"lpacPayments"},
    {L"LPAC - PnP Notifications", L"lpacPnPNotifications"},
    {L"LPAC - Printing", L"lpacPrinting"},
    {L"LPAC - Services Management", L"lpacServicesManagement"},
    {L"LPAC - Session Management", L"lpacSessionManagement"},
    {L"LPAC - Web Platform", L"lpacWebPlatform"},
    {L"accessoryManager", L"accessoryManager"},
    {L"activateAsUser", L"activateAsUser"},
    {L"activity", L"activity"},
    {L"activityData", L"activityData"},
    {L"activitySystem", L"activitySystem"},
    {L"allAppMods", L"allAppMods"},
    {L"allJoyn", L"allJoyn"},
    {L"allowElevation", L"allowElevation"},
    {L"appBroadcast", L"appBroadcast"},
    {L"appBroadcastServices", L"appBroadcastServices"},
    {L"appBroadcastSettings", L"appBroadcastSettings"},
    {L"appCaptureServices", L"appCaptureServices"},
    {L"appCaptureSettings", L"appCaptureSettings"},
    {L"appDiagnostics", L"appDiagnostics"},
    {L"appLicensing", L"appLicensing"},
    {L"appManagementSystem", L"appManagementSystem"},
    {L"applicationDefaults", L"applicationDefaults"},
    {L"applicationViewActivation", L"applicationViewActivation"},
    {L"appointmentsSystem", L"appointmentsSystem"},
    {L"audioDeviceConfiguration", L"audioDeviceConfiguration"},
    {L"automatedAppLaunch", L"automatedAppLaunch"},
    {L"backgroundMediaPlayback", L"backgroundMediaPlayback"},
    {L"backgroundMediaRecording", L"backgroundMediaRecording"},
    {L"backgroundSpatialPerception", L"backgroundSpatialPerception"},
    {L"backgroundVoIP", L"backgroundVoIP"},
    {L"biometricSystem", L"biometricSystem"},
    {L"blockedChatMessages", L"blockedChatMessages"},
    {L"bluetooth", L"bluetooth"},
    {L"bluetooth.genericAttributeProfile", L"bluetooth.genericAttributeProfile"},
    {L"bluetooth.rfcomm", L"bluetooth.rfcomm"},
    {L"bluetoothAdapter", L"bluetoothAdapter"},
    {L"bluetoothDeviceSettings", L"bluetoothDeviceSettings"},
    {L"bluetoothSync", L"bluetoothSync"},
    {L"bootstrapNetworkConnection", L"bootstrapNetworkConnection"},
    {L"broadFileSystemAccess", L"broadFileSystemAccess"},
    {L"browserAppList", L"browserAppList"},
    {L"browserCredentials", L"browserCredentials"},
    {L"cameraProcessingExtension", L"cameraProcessingExtension"},
    {L"capabilityAccessConsentDeviceSettings", L"capabilityAccessConsentDeviceSettings"},
    {L"cellularData", L"cellularData"},
    {L"cellularDeviceControl", L"cellularDeviceControl"},
    {L"cellularDeviceIdentity", L"cellularDeviceIdentity"},
    {L"cellularMessaging", L"cellularMessaging"},
    {L"chat", L"chat"},
    {L"chatSystem", L"chatSystem"},
    {L"childWebContent", L"childWebContent"},
    {L"chromeInstallFiles", L"chromeInstallFiles"},
    {L"cloudExperienceHost", L"cloudExperienceHost"},
    {L"cloudStore", L"cloudStore"},
    {L"codeGeneration", L"codeGeneration"},
    {L"comPort", L"comPort"},
    {L"componentUiInWebContent", L"componentUiInWebContent"},
    {L"confirmAppClose", L"confirmAppClose"},
    {L"constrainedImpersonation", L"constrainedImpersonation"},
    {L"contactsSystem", L"contactsSystem"},
    {L"contentDeliveryManagerSettings", L"contentDeliveryManagerSettings"},
    {L"contentRestrictions", L"contentRestrictions"},
    {L"coreShell", L"coreShell"},
    {L"cortanaPermissions", L"cortanaPermissions"},
    {L"cortanaSettings", L"cortanaSettings"},
    {L"cortanaSpeechAccessory", L"cortanaSpeechAccessory"},
    {L"cortanaSurface", L"cortanaSurface"},
    {L"curatedTileCollections", L"curatedTileCollections"},
    {L"customInstallActions", L"customInstallActions"},
    {L"dateAndTimeDeviceSettings", L"dateAndTimeDeviceSettings"},
    {L"dependencyTarget", L"dependencyTarget"},
    {L"developerSettings", L"developerSettings"},
    {L"developmentModeNetwork", L"developmentModeNetwork"},
    {L"deviceEncryptionManagement", L"deviceEncryptionManagement"},
    {L"deviceIdentityManagement", L"deviceIdentityManagement"},
    {L"deviceLockManagement", L"deviceLockManagement"},
    {L"deviceManagementAdministrator", L"deviceManagementAdministrator"},
    {L"deviceManagementDeviceLockPolicies", L"deviceManagementDeviceLockPolicies"},
    {L"deviceManagementDmAccount", L"deviceManagementDmAccount"},
    {L"deviceManagementEmailAccount", L"deviceManagementEmailAccount"},
    {L"deviceManagementFoundation", L"deviceManagementFoundation"},
    {L"deviceManagementRegistration", L"deviceManagementRegistration"},
    {L"deviceManagementWapSecurityPolicies", L"deviceManagementWapSecurityPolicies"},
    {L"devicePortalProvider", L"devicePortalProvider"},
    {L"deviceProvisioningAdministrator", L"deviceProvisioningAdministrator"},
    {L"deviceUnlock", L"deviceUnlock"},
    {L"diagnostics", L"diagnostics"},
    {L"displayDeviceSettings", L"displayDeviceSettings"},
    {L"dualSimTiles", L"dualSimTiles"},
    {L"email", L"email"},
    {L"emailSystem", L"emailSystem"},
    {L"enterpriseCloudSSO", L"enterpriseCloudSSO"},
    {L"enterpriseDataPolicy", L"enterpriseDataPolicy"},
    {L"enterpriseDeviceLockdown", L"enterpriseDeviceLockdown"},
    {L"eraApplication", L"eraApplication"},
    {L"exclusiveResource", L"exclusiveResource"},
    {L"expandedResources", L"expandedResources"},
    {L"extendedBackgroundTaskTime", L"extendedBackgroundTaskTime"},
    {L"extendedExecutionBackgroundAudio", L"extendedExecutionBackgroundAudio"},
    {L"extendedExecutionCritical", L"extendedExecutionCritical"},
    {L"extendedExecutionUnconstrained", L"extendedExecutionUnconstrained"},
    {L"featureStagingInfo", L"featureStagingInfo"},
    {L"feedbackLogCollection", L"feedbackLogCollection"},
    {L"firstSignInSettings", L"firstSignInSettings"},
    {L"flashPlayerSupport", L"flashPlayerSupport"},
    {L"fullFileSystemAccess", L"fullFileSystemAccess"},
    {L"gameBarServices", L"gameBarServices"},
    {L"gameConfigStoreManagement", L"gameConfigStoreManagement"},
    {L"gameList", L"gameList"},
    {L"gameMonitor", L"gameMonitor"},
    {L"gamingContainerResources", L"gamingContainerResources"},
    {L"gazeInput", L"gazeInput"},
    {L"globalMediaControl", L"globalMediaControl"},
    {L"graphicsCapture", L"graphicsCapture"},
    {L"hevcPlayback", L"hevcPlayback"},
    {L"hfxSystem", L"hfxSystem"},
    {L"hidTelephony", L"hidTelephony"},
    {L"holographicCompositor", L"holographicCompositor"},
    {L"holographicCompositorSystem", L"holographicCompositorSystem"},
    {L"humanInterfaceDevice", L"humanInterfaceDevice"},
    {L"imeSystem", L"imeSystem"},
    {L"inProcessMediaExtension", L"inProcessMediaExtension"},
    {L"indexedContent", L"indexedContent"},
    {L"inputForegroundObservation", L"inputForegroundObservation"},
    {L"inputInjection", L"inputInjection"},
    {L"inputInjectionBrokered", L"inputInjectionBrokered"},
    {L"inputObservation", L"inputObservation"},
    {L"inputSettings", L"inputSettings"},
    {L"inputSuppression", L"inputSuppression"},
    {L"interopServices", L"interopServices"},
    {L"keyboardDeviceSettings", L"keyboardDeviceSettings"},
    {L"kinectAudio", L"kinectAudio"},
    {L"kinectExpressions", L"kinectExpressions"},
    {L"kinectFace", L"kinectFace"},
    {L"kinectGamechat", L"kinectGamechat"},
    {L"kinectRequired", L"kinectRequired"},
    {L"kinectVideo", L"kinectVideo"},
    {L"kinectVision", L"kinectVision"},
    {L"languageAndRegionDeviceSettings", L"languageAndRegionDeviceSettings"},
    {L"languageSettings", L"languageSettings"},
    {L"liveIdService", L"liveIdService"},
    {L"localExperienceInternal", L"localExperienceInternal"},
    {L"localSystemServices", L"localSystemServices"},
    {L"location", L"location"},
    {L"locationHistory", L"locationHistory"},
    {L"locationSystem", L"locationSystem"},
    {L"lockScreenCreatives", L"lockScreenCreatives"},
    {L"lowLevel", L"lowLevel"},
    {L"lowLevelDevices", L"lowLevelDevices"},
    {L"microphone", L"microphone"},
    {L"microsoftEdgeRemoteDebugging", L"microsoftEdgeRemoteDebugging"},
    {L"mixedRealityEnvironmentInternal", L"mixedRealityEnvironmentInternal"},
    {L"mmsTransportSystem", L"mmsTransportSystem"},
    {L"modifiableApp", L"modifiableApp"},
    {L"multiplaneOverlay", L"multiplaneOverlay"},
    {L"muma", L"muma"},
    {L"networkConnectionManagerProvisioning", L"networkConnectionManagerProvisioning"},
    {L"networkDataPlanProvisioning", L"networkDataPlanProvisioning"},
    {L"networkDataUsageManagement", L"networkDataUsageManagement"},
    {L"networkDeviceSettings", L"networkDeviceSettings"},
    {L"networkDiagnostics", L"networkDiagnostics"},
    {L"networkingVpnProvider", L"networkingVpnProvider"},
    {L"nfcSystem", L"nfcSystem"},
    {L"notificationsDeviceSettings", L"notificationsDeviceSettings"},
    {L"objects3D", L"objects3D"},
    {L"oemDeployment", L"oemDeployment"},
    {L"oemPublicDirectory", L"oemPublicDirectory"},
    {L"offlineMapsManagement", L"offlineMapsManagement"},
    {L"oneProcessVoIP", L"oneProcessVoIP"},
    {L"optical", L"optical"},
    {L"pacJsWorker", L"pacJsWorker"},
    {L"packageContents", L"packageContents"},
    {L"packageManagement", L"packageManagement"},
    {L"packagePolicySystem", L"packagePolicySystem"},
    {L"packageQuery", L"packageQuery"},
    {L"packageWriteRedirectionCompatibilityShim", L"packageWriteRedirectionCompatibilityShim"},
    {L"packagedServices", L"packagedServices"},
    {L"perceptionMonitoring", L"perceptionMonitoring"},
    {L"perceptionSensorsExperimental", L"perceptionSensorsExperimental"},
    {L"perceptionSystem", L"perceptionSystem"},
    {L"personalizationDeviceSettings", L"personalizationDeviceSettings"},
    {L"phoneCall", L"phoneCall"},
    {L"phoneCallHistory", L"phoneCallHistory"},
    {L"phoneCallHistoryPublic", L"phoneCallHistoryPublic"},
    {L"phoneCallHistorySystem", L"phoneCallHistorySystem"},
    {L"phoneCallSystem", L"phoneCallSystem"},
    {L"phoneLineTransportManagement", L"phoneLineTransportManagement"},
    {L"pointOfService", L"pointOfService"},
    {L"powerDeviceSettings", L"powerDeviceSettings"},
    {L"preemptiveCamera", L"preemptiveCamera"},
    {L"previewHfx", L"previewHfx"},
    {L"previewInkWorkspace", L"previewInkWorkspace"},
    {L"previewPenWorkspace", L"previewPenWorkspace"},
    {L"previewStore", L"previewStore"},
    {L"previewUiComposition", L"previewUiComposition"},
    {L"projectionDeviceSettings", L"projectionDeviceSettings"},
    {L"protectedApp", L"protectedApp"},
    {L"proximity", L"proximity"},
    {L"radios", L"radios"},
    {L"recordedCallsFolder", L"recordedCallsFolder"},
    {L"regionSettings", L"regionSettings"},
    {L"registryRead", L"registryRead"},
    {L"relatedPackages", L"relatedPackages"},
    {L"remoteFileAccess", L"remoteFileAccess"},
    {L"remotePassportAuthentication", L"remotePassportAuthentication"},
    {L"remoteSystem", L"remoteSystem"},
    {L"resetPhone", L"resetPhone"},
    {L"runFullTrust", L"runFullTrust"},
    {L"screenDuplication", L"screenDuplication"},
    {L"searchSettings", L"searchSettings"},
    {L"secondaryAuthenticationFactor", L"secondaryAuthenticationFactor"},
    {L"secureAssessment", L"secureAssessment"},
    {L"sensors.custom", L"sensors.custom"},
    {L"serialCommunication", L"serialCommunication"},
    {L"sessionImpersonation", L"sessionImpersonation"},
    {L"settingSyncConfiguration", L"settingSyncConfiguration"},
    {L"sharedMachineKeysCapability", L"sharedMachineKeysCapability"},
    {L"shellDisplayManagement", L"shellDisplayManagement"},
    {L"shellExperience", L"shellExperience"},
    {L"shellExperienceComposer", L"shellExperienceComposer"},
    {L"slapiQueryLicenseValue", L"slapiQueryLicenseValue"},
    {L"smbios", L"smbios"},
    {L"sms", L"sms"},
    {L"smsSend", L"smsSend"},
    {L"smsSystem", L"smsSystem"},
    {L"smsTransportSystem", L"smsTransportSystem"},
    {L"spatialPerception", L"spatialPerception"},
    {L"startScreenManagement", L"startScreenManagement"},
    {L"storeAppInstall", L"storeAppInstall"},
    {L"storeAppInstallation", L"storeAppInstallation"},
    {L"storeConfiguration", L"storeConfiguration"},
    {L"storeLicenseManagement", L"storeLicenseManagement"},
    {L"storeOptionalPackageInstallManagement", L"storeOptionalPackageInstallManagement"},
    {L"systemDialog", L"systemDialog"},
    {L"systemDialogEmergency", L"systemDialogEmergency"},
    {L"systemManagement", L"systemManagement"},
    {L"systemRegistrar", L"systemRegistrar"},
    {L"targetedContent", L"targetedContent"},
    {L"targetedContentSubscription", L"targetedContentSubscription"},
    {L"teamEditionDeviceCredential", L"teamEditionDeviceCredential"},
    {L"teamEditionExperience", L"teamEditionExperience"},
    {L"teamEditionView", L"teamEditionView"},
    {L"telemetryData", L"telemetryData"},
    {L"terminalPowerManagement", L"terminalPowerManagement"},
    {L"thumbnailCache", L"thumbnailCache"},
    {L"timezone", L"timezone"},
    {L"uiAccess", L"uiAccess"},
    {L"uiAutomationSystem", L"uiAutomationSystem"},
    {L"unvirtualizedResources", L"unvirtualizedResources"},
    {L"unzipFile", L"unzipFile"},
    {L"updateAndSecurityDeviceSettings", L"updateAndSecurityDeviceSettings"},
    {L"usb", L"usb"},
    {L"userAccountInformation", L"userAccountInformation"},
    {L"userDataAccountSetup", L"userDataAccountSetup"},
    {L"userDataAccountsProvider", L"userDataAccountsProvider"},
    {L"userDataSystem", L"userDataSystem"},
    {L"userDataTasks", L"userDataTasks"},
    {L"userDataTasksSystem", L"userDataTasksSystem"},
    {L"userManagementSystem", L"userManagementSystem"},
    {L"userNotificationListener", L"userNotificationListener"},
    {L"userPrincipalName", L"userPrincipalName"},
    {L"userSigninSupport", L"userSigninSupport"},
    {L"userSystemId", L"userSystemId"},
    {L"userWebAccounts", L"userWebAccounts"},
    {L"visualElementsSystem", L"visualElementsSystem"},
    {L"visualVoiceMail", L"visualVoiceMail"},
    {L"vmWorkerProcess", L"vmWorkerProcess"},
    {L"voipCall", L"voipCall"},
    {L"walletSystem", L"walletSystem"},
    {L"webPlatformMediaExtension", L"webPlatformMediaExtension"},
    {L"webcam", L"webcam"},
    {L"wiFiControl", L"wiFiControl"},
    {L"wiFiDirect", L"wiFiDirect"},
    {L"wifiData", L"wifiData"},
    {L"windowManagement", L"windowManagement"},
    {L"windowManagementSystem", L"windowManagementSystem"},
    {L"windowsHelloCredentialAccess", L"windowsHelloCredentialAccess"},
    {L"windowsPerformanceCounters", L"windowsPerformanceCounters"},
    {L"xboxAccessoryManagement", L"xboxAccessoryManagement"},
    {L"xboxBroadcaster", L"xboxBroadcaster"},
    {L"xboxGameSpeechWindow", L"xboxGameSpeechWindow"},
    {L"xboxLiveAuthenticationProvider", L"xboxLiveAuthenticationProvider"},
    {L"xboxSystemApplicationClipQuery", L"xboxSystemApplicationClipQuery"},
    {L"xboxTrackingStream", L"xboxTrackingStream"}
    //
};
} // namespace priv

#endif